import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'dot game',
  description: 'Generated by create kwon',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='manifest' href='/manifest.json' />

      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
